# Generated by Django 3.2 on 2022-11-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('sku', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('ean', models.IntegerField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('brand', models.CharField(blank=True, max_length=25)),
                ('warranty_time', models.IntegerField(blank=True)),
                ('height', models.DecimalField(decimal_places=3, max_digits=7)),
                ('width', models.DecimalField(decimal_places=3, max_digits=7)),
                ('length', models.DecimalField(decimal_places=3, max_digits=7)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=7)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('special_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('quantity', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['id'],
            },
        ),
    ]
